version: '3.8'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
